### ISSUE TITLE
Scanner nevers scans when using the Structures Scanner Module

### ISSUE THREAD

**Issue by calloatti** [MightyPirates/Scannable#39] opened 2018-04-03 00:10 UTC
Minecraft 1.12.2
Scannable-MC1.12-1.6.3.17

When using the Structures module, when pressing right mouse button and keeping it down, the scanner charges and then nothing happens, it stays at 100% charge until the right mouse button is released.

![2018-04-02_21 02 43](https://user-images.githubusercontent.com/12817862/38222184-b3a2a64c-36b9-11e8-877a-f0f4d79be72b.png)

![2018-04-02_21 03 07](https://user-images.githubusercontent.com/12817862/38222204-c2fba0bc-36b9-11e8-8618-3a505c378e51.png)

Other modules work. Nothing shows in the log.

**Comment by fnuecke** [comment] 2018-05-26 20:09
I'm afraid I cannot reproduce this, is this also the case when you try this with just Scannable, no other mods? If it works then, could you try narrowing it down to which mod combination causes this issue? Thanks.

**Comment by fnuecke** [comment] 2018-08-13 15:04
Closing due to missing feedback.

**Closed as completed by fnuecke** 2018-08-13 15:04 UTC
