### ISSUE TITLE
Config Changes Are Always Overwritten (1.12) 1.4.0.5

### ISSUE THREAD

**Issue by marikc0** [MightyPirates/Scannable#25] opened 2017-07-26 08:59 UTC
All power use config changes are overwritten once the game is loaded again. Rare/Common ore settings are not. I've changed this about 5 times and every time it is overwritten again.

**Comment by fnuecke** [comment] 2017-08-14 11:12
I'm afraid I can't reproduce that; and I'm not sure what I could do about it anyway, since I'm using the Forge config system with no custom logic thrown in at all, really.

What are your exact steps here? Start MC, ..., Quit MC, Start MC, ...?

**Comment by fnuecke** [comment] 2018-01-24 18:10
No further input, closing.

**Closed as completed by fnuecke** 2018-01-24 18:10 UTC
