### ISSUE TITLE
Crash using the scanner

### ISSUE THREAD

**Issue by th4umiel** [MightyPirates/Scannable#34] opened 2017-11-13 12:01 UTC
The scanner does the charging then it crashes the game.

https://pastebin.com/Fgxs9QW6

**Comment by fnuecke** [comment] 2017-11-13 17:41
Can't reproduce (tested SP and MP), and I don't really see how that could normally happen (Scannable only triggers the sound on the client).

Please see if this also happens without any other mods present, and if it does not, if you can isolate the mod that causes this behavior (remove one half of the mods, if it doesn't break anymore, try the other half, repeat). Thanks.

**Comment by th4umiel** [comment] 2017-11-13 21:37
I will do some testing as soon as possible :) for the moment, thanks for the quick response!

**Comment by fnuecke** [comment] 2018-01-24 18:10
No further input an pastebin link is dead, closing.

**Closed as completed by fnuecke** 2018-01-24 18:10 UTC
